### ISSUE TITLE
0.1.5 release has issues with document symbols for Rascal files

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#116]
This is from the `Log (Extension Host)` tab of the `Output` View:

```
[2021-12-17 12:19:05.744] [exthost] [error] Canceled: Canceled
	at LanguageClient.makeCancelError (/Users/jurgenv/.vscode/extensions/usethesource.rascalmpl-0.1.5/node_modules/vscode-languageclient/lib/common/client.js:2666:24)
	at LanguageClient.handleFailedRequest (/Users/jurgenv/.vscode/extensions/usethesource.rascalmpl-0.1.5/node_modules/vscode-languageclient/lib/common/client.js:2656:28)
	at /Users/jurgenv/.vscode/extensions/usethesource.rascalmpl-0.1.5/node_modules/vscode-languageclient/lib/common/client.js:1115:39
	at async s.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:87704)
```

**Comment by DavyLandman** [comment]
I cannot reproduce this.

![image](https://user-images.githubusercontent.com/179603/146654143-7d7479b9-c854-4390-818b-54111d6cfbf2.png)

do you have some more log information from the LSP server output? That might help figure out what is going on. 

Does it also mean your outline is broken?

**Comment by jurgenvinju** [comment]
In my simple project (code-as-data-demo) it all works fine. Outline and everything.

**Comment by jurgenvinju** [comment]
Closing this for now; no easily reproducible case.
