### ISSUE TITLE
jump-to-definition also works to library modules and inside library modules

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#150]
it does not work _inside_ libraries modules. Only _to_ library modules.

**Comment by DavyLandman** [comment]
As the interface for makeSummary changed? or maybe the result of it?

```
2022-04-21 11:26:46,223 [pool-2-thread-12] ERROR - org.rascalmpl.vscode.lsp.util.EvaluatorUtil Rascal makeSummary failed
org.rascalmpl.interpreter.staticErrors.UnexpectedType: Expected rel[loc scope,str id,str orgId,IdRole idRole,loc defined,DefInfo defInfo], but got rel[loc,str,IdRole,loc,DefInfo]
Advice: |http://tutor.rascal-mpl.org/Errors/Static/UnexpectedType/UnexpectedType.html|
	at Summary.?(/lang/rascalcore/check/Summary.rsc:47) ~[?:?]
	at org.rascalmpl.interpreter.result.Result.<init>(Result.java:91) ~[rascal.jar:?]
	at org.rascalmpl.interpreter.result.ElementResult.<init>(ElementResult.java:43) ~[rascal.jar:?]
	at org.rascalmpl.interpreter.result.CollectionResult.<init>(CollectionResult.java:31) ~[rascal.jar:?]
	at org.rascalmpl.interpreter.result.SetOrRelationResult.<init>(SetOrRelationResult.java:29) ~[rascal.jar:?]
```

**Comment by DavyLandman** [comment]
ah, this might have been outdated tpl files popping up.

**Comment by rodinaarssen** [comment]
That looks like a change in TypePal that @PaulKlint introduced recently (the addition of `str orgId`)

**Comment by DavyLandman** [comment]
Ah, I know what is happening.

rascal 0.23.0 was build with previous version of rascal-core (and maven plugin). So the tpls files inside the rascal.jar is not something the new rascal-core can handle.

**Comment by jurgenvinju** [comment]
Aha. we are half-way a bootstrap. So that also breaks the same features in rascal-eclipse.

**Comment by jurgenvinju** [comment]
To fix this, I will:

* [ ] release a new version of rascal-core
* [ ] include that in rascal-maven-plugin
* [ ] upgrade version of rascal-maven-plugin in typepal and rascal
* [ ] release typepal 
* [ ] release rascal
* [ ] upgrade dependencies in rascal-lsp for rascal, typepal and rascal-core
* [ ] upgrade dependencies in rascal-eclipse for rascal, typepal and rascal-core
* [ ] re-release rascal-eclipse
* [ ] release rascal-language-servers (the other manual tests I have succeed now. If you have more, don't hesitate to add them)

**Comment by DavyLandman** [comment]
do we care about the rascal-core tpls?

**Comment by jurgenvinju** [comment]
you are right. we talked on the phone, but for future reference: rascal-core was improved with a lot fewer debug prints in the meantime, which could have an effect on GitHub Action efficiency so I'm including those improvements in the bootstrap cycle for that reason only.
