### ISSUE TITLE
NPE in :edit command in terminal in VScode

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#228]
**Describe the bug**

rascal>:edit demo::lang::Pico::TypeCheck
java.lang.NullPointerException
(internal error)
        at $shell$(|main://$shell$|)

java.lang.NullPointerException
        at org.rascalmpl.uri.URIResolverRegistry.logicalToPhysical(URIResolverRegistry.java:324)
        at org.rascalmpl.vscode.lsp.terminal.TerminalIDEClient.edit(TerminalIDEClient.java:104)
        at org.rascalmpl.interpreter.Evaluator$SaveWarningsMonitor.edit(Evaluator.java:1855)
        at org.rascalmpl.interpreter.Evaluator$SaveWarningsMonitor.edit(Evaluator.java:1855)
        at org.rascalmpl.interpreter.Evaluator$SaveWarningsMonitor.edit(Evaluator.java:1855)
        at org.rascalmpl.interpreter.Evaluator$SaveWarningsMonitor.edit(Evaluator.java:1855)
        at org.rascalmpl.semantics.dynamic.ShellCommand$Edit.interpret(ShellCommand.java:50)

**Comment by DavyLandman** [comment]
is the REPL connected to the project? (and we should make that more visible).

**Comment by DavyLandman** [comment]
looking at the code, you should see a message: `warning demo::lang::Pico::TypeCheck can not be found in your search path` in the output window of rascal.

I've fixed the NPE, but in the end, rascal couldn't find the `TypeCheck` module with it's current resolver. my best guess: this REPL was not started in the context where it could find that module.

**Comment by jurgenvinju** [comment]
I auto-completed the module name, so that's not possible.

**Comment by DavyLandman** [comment]
Where is it referenced?

**Comment by jurgenvinju** [comment]
I'm still digging.. don't know.
