### ISSUE TITLE
executeCommands prints interpreter/java stacktrace instead of Rascal stack trace

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#234]
**Describe the bug**

> Request workspace/executeCommand failed.

```
java.util.concurrent.CompletionException: org.rascalmpl.exceptions.Throw: |std:///util/Math.rsc|:82,0: Java("IllegalArgumentException","bound must be positive")
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This should show the Rascal stack trace since the user is calling a rascal command evaluator. Now we can't see which
functions are leading up to the exception.

It is possible that more LSP calls in the parametrized LSP server should print Rascal stack traces rather than Java stack traces.

**Comment by jurgenvinju** [comment]
The code was factored very well, which made it easy to make this change. However, for all LSP callbacks we will now _only_ have Rascal stack-traces. If there is a bug in the interpreter, it must be debugged from calling the function from the terminal and enabling `errors` via `:set errors true`.

**Comment by DavyLandman** [comment]
Happy to hear that.
