### ISSUE TITLE
Project URI failure on Windows

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#250]
**Describe the bug**

```
2023-04-21 11:17:38,765 [ForkJoinPool.commonPool-worker-13] ERROR - org.eclipse.lsp4j.jsonrpc.RemoteEndpoint Internal error: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /y:/HSI/configuration/rascal_ccsl/mt.ccsl

java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /y:/HSI/configuration/rascal_ccsl/movementtypes.ccsl

  at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]

  at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]

  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]

  at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]

  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]

  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]

  at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]

  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]

  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /y:/HSI/configuration/rascal_ccsl/mt.ccsl

  at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]

  at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]

  at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]

  at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]

  at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[?:?]

  at java.nio.file.Path.of(Path.java:147) ~[?:?]

  at java.nio.file.Paths.get(Paths.java:69) ~[?:?]

  at org.rascalmpl.uri.file.FileURIResolver.created(FileURIResolver.java:164) ~[rascal.jar:?]

  at org.rascalmpl.uri.URIResolverRegistry.created(URIResolverRegistry.java:690) ~[rascal.jar:?]

  at org.rascalmpl.vscode.lsp.IRascalFileSystemServices.lambda$stat$3(IRascalFileSystemServices.java:130) ~[rascal-lsp.jar:?]

  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]

  ... 6 more

2023-04-21 11:17:39,988 [ForkJoinPool.commonPool-worker-5] ERROR - org.eclipse.lsp4j.jsonrpc.RemoteEndpoint Internal error: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /y:/HSI/configuration/rascal_ccsl/mt.ccsl

java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /y:/HSI/configuration/rascal_ccsl/mt.ccsl

  at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]

  at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]

  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]

  at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]

  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]

  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]

  at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]

  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]

  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /y:/HSI/configuration/rascal_ccsl/mt.ccsl

  at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]

  at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]

  at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]

  at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]

  at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[?:?]

  at java.nio.file.Path.of(Path.java:147) ~[?:?]

  at java.nio.file.Paths.get(Paths.java:69) ~[?:?]

  at org.rascalmpl.uri.file.FileURIResolver.created(FileURIResolver.java:164) ~[rascal.jar:?]

  at org.rascalmpl.uri.URIResolverRegistry.created(URIResolverRegistry.java:690) ~[rascal.jar:?]

  at org.rascalmpl.vscode.lsp.IRascalFileSystemServices.lambda$stat$3(IRascalFileSystemServices.java:130) ~[rascal-lsp.jar:?]

  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]

  ... 6 more

2023-04-21 11:17:47,960 [pool-3-thread-1] WARN - org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint Unsupported request method: rascal/filesystem/unwatch
```

**Comment by jurgenvinju** [comment]
The absolute (broken) file URI comes from a `project` URI that is produced from a reference location produced by TypePal. So this happens when jumping between files using the TypePal model. The project URI is correct.

**Comment by jurgenvinju** [comment]
Reading the code from `WindowsPathParser` reveals that windows paths should not have a leading slash.

**Comment by DavyLandman** [comment]
Is that when using the latest rascal? since there are some bugfixes done there recently?

**Comment by DavyLandman** [comment]
we should write a test for this, since rascal tests are also executed on windows.

**Comment by jurgenvinju** [comment]
No this is caused by a young but not recent addition, the implementation of the `watch` function:

```
@Override
	public long created(ISourceLocation uri) throws IOException {
		BasicFileAttributeView basicfile = Files.getFileAttributeView(Paths.get(getPath(uri)), BasicFileAttributeView.class, LinkOption.NOFOLLOW_LINKS);
        BasicFileAttributes attr = basicfile.readAttributes() ;
        return attr.creationTime().toMillis();
	}
	
	@Override
	public String[] list(ISourceLocation uri) {
		return new File(getPath(uri)).list();
	}
```

As you can see we are using `Paths.get(getPath(uri))` to get a `Path` while the older code uses `new File(getPath(uri))`. It seems clear that the `new File` functionality has a different parser for absolute file paths that contain drive letters `/C:` than the nio `Paths.get` feature.

**Comment by jurgenvinju** [comment]
The watch functionality is activated because it is a about a (logical) project URI. This file is opened by reference resolving by VScode, who then asks for the VFS implementation in Java over the LSP, which then is translates to an absolute file URI, which is then parsed incorrectly by the `watch`  function's call to `Paths.get`

**Comment by jurgenvinju** [comment]
So the tests should test the watch functionality of file URIs that are produced from resolving project URIs

**Comment by jurgenvinju** [comment]
Can't fix this today probably, but there are people eagerly waiting. This blocks all reference resolving between DSL files in the VScode extension.

**Comment by DavyLandman** [comment]
if you need help. you need to share a repo case. preferably in the form of a test. because I cannot reproduce this with the information you've written down.

I'm missing version information, actual loc examples, and preferably a set of test of things to do to reproduce it.

**Comment by jurgenvinju** [comment]
So far I could not trigger the bug in the rascal project independent of the project URI's implementation in rascal-lsp. This seems to be the code that introduces the unexpected encoding of windows paths:

```
@Override
    public CompletableFuture<SourceLocationParameter> resolveProjectLocation(SourceLocationParameter loc) {
        logger.trace("resolveProjectLocation({})", loc);
        ISourceLocation input = loc.getLocation();
        String projectName = input.getAuthority();

        for (var folder: workspaceService.workspaceFolders()) {
            if (folder.getName().equals(projectName)) {
                return CompletableFuture.completedFuture(buildProjectChildLoc(folder, input, loc));
            }
        }
        return CompletableFuture.completedFuture(loc);
    }

    private SourceLocationParameter buildProjectChildLoc(WorkspaceFolder folder, ISourceLocation input, SourceLocationParameter fallback) {
        try {
            ISourceLocation root = URIUtil.createFromURI(folder.getUri());
            ISourceLocation newLoc = URIUtil.getChildLocation(root, input.getPath());
            return new SourceLocationParameter(newLoc);
        } catch (URISyntaxException e) {
            logger.catching(e);
            return fallback;
        }
    }
```

That that comes directly from `WorkspaceFolder` which is sent to us via the JSON-RPC bridge as a string.

**Comment by jurgenvinju** [comment]
This is a piece of the Windows implementation of `new File`

```
 // Remove duplicate and redundant separator characters.
 284:   private String normalizePath(String p)
 285:   {
 286:     // On Windows, convert any '/' to '\'.  This appears to be the same logic
 287:     // that Sun's Win32 Java performs.
 288:     if (separatorChar == '\\')
 289:       {
 290:         p = p.replace ('/', '\\');
 291:     // We have to special case the "\c:" prefix.
 292:     if (p.length() > 2 && p.charAt(0) == '\\' &&
 293:         ((p.charAt(1) >= 'a' && p.charAt(1) <= 'z') ||
 294:         (p.charAt(1) >= 'A' && p.charAt(1) <= 'Z')) &&
 295:         p.charAt(2) == ':')
 296:       p = p.substring(1);
 297:       }
```

Here we clearly see how the `/c:` notation is supported, where it wasn't supported by the `Paths.get` parser.

**Comment by jurgenvinju** [comment]
Made a failing test! https://github.com/usethesource/rascal/actions/runs/4779131423/jobs/8496025078 excellent :-)
