### ISSUE TITLE
Unsupported splice pattern causes NULL pointer exception inside interpreter

### ISSUE THREAD

**Issue by leegbestand** [usethesource/rascal-language-servers#493]
**Describe the bug**

Doing a splice in a function patterns causes a null error inside the interpreter

**To Reproduce**
Define the following function inside a module and try to import the module in a REPL. 
```
void spliceNull(*10) = 10;
```

1. Define the following module:
```
module Main

int spliceNull(*10) = 10;
```
2. import the module into a REPL.
3. See a null error inside the REPL console:
```
Could not load Main due to: Unexpected error in Rascal interpreter: null at |prompt:///|(0,12,<1,0>,<1,12>)
org.rascalmpl.exceptions.ImplementationError: Unexpected error in Rascal interpreter: null
        at org.rascalmpl.semantics.dynamic.Expression$Splice.typeOf(Expression.java:1875)
        at org.rascalmpl.semantics.dynamic.Formals$Default.typeOf(Formals.java:42)
        at org.rascalmpl.semantics.dynamic.Parameters$Default.typeOf(Parameters.java:35)
        at org.rascalmpl.semantics.dynamic.Signature$NoThrows.typeOf(Signature.java:50)
        at org.rascalmpl.interpreter.result.RascalFunction.<init>(RascalFunction.java:91)
```

**Expected behavior**
A clear error message indicating the invalidity of the splice pattern.

**Desktop (please complete the following information):**
 - Context: VS Code 1.94.1
 - Rascal Version 0.34.2 in Rascal-lsp 2.20.2

**Additional context**
The LSP server does handle this and highlights the piece of code with an error indicating invalid splice.

**Comment by jurgenvinju** [comment]
Nice catch @leegbestand
