### ISSUE TITLE
resolveProjectLocation from terminal deadlocks

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#73]
```
rascal>createM3FromDirectory(|project://vallang|)
...
```

jstack LSPTerminal:

```
"main" #1 prio=5 os_prio=31 tid=0x00007ff79780b000 nid=0x2903 waiting on condition [0x000070000a218000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000077d1f43b8> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.rascalmpl.vscode.lsp.terminal.TerminalIDEClient.resolveProjectLocation(TerminalIDEClient.java:81)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1$$Lambda$39/1282811396.apply(Unknown Source)
        at org.rascalmpl.vscode.lsp.uri.ProjectURIResolver.resolve(ProjectURIResolver.java:45)
        at org.rascalmpl.uri.URIResolverRegistry.physicalLocation(URIResolverRegistry.java:283)
        at org.rascalmpl.uri.URIResolverRegistry.safeResolve(URIResolverRegistry.java:339)
        at org.rascalmpl.uri.URIResolverRegistry.isDirectory(URIResolverRegistry.java:485)
        at org.rascalmpl.library.Prelude.isDirectory(Prelude.java:1057)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.rascalmpl.interpreter.result.JavaMethod.invoke(JavaMethod.java:243)
        at org.rascalmpl.interpreter.result.JavaMethod.call(JavaMethod.java:165)
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:535)
        at org.rascalmpl.interpreter.matching.BasicBooleanResult.next(BasicBooleanResult.java:48)
        at org.rascalmpl.interpreter.matching.NotResult.next(NotResult.java:54)
        at org.rascalmpl.semantics.dynamic.Statement$IfThen.interpret(Statement.java:600)
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:388)
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:329)
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:535)
        at org.rascalmpl.semantics.dynamic.Command$Expression.interpret(Command.java:61)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:1119)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:989)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:944)
        at org.rascalmpl.repl.RascalInterpreterREPL.evalStatement(RascalInterpreterREPL.java:131)
        - locked <0x00000006c04a0fc0> (a org.rascalmpl.interpreter.Evaluator)
        at org.rascalmpl.repl.BaseRascalREPL.handleInput(BaseRascalREPL.java:106)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1.handleInput(LSPTerminalREPL.java:169)
        at org.rascalmpl.repl.BaseREPL.handleInput(BaseREPL.java:180)
        at org.rascalmpl.repl.BaseREPL.run(BaseREPL.java:347)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.main(LSPTerminalREPL.java:238)
```

**Comment by jurgenvinju** [comment]
this was due to an annotation error in the JSON-RPC bridge
