### ISSUE TITLE
Paramateric language server cannot handle new projects added to the workspace after startup

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#87]
If you add a new project to the workspace, and then run registerLanguage for something in that project, you will get the the following exception in the P-LSP server:

```
Error data: "java.util.concurrent.CompletionException: org.rascalmpl.uri.UnsupportedSchemeException: Unsupported scheme project
  at org.rascalmpl.vscode.lsp.IRascalFileSystemServices.lambda$stat$3(IRascalFileSystemServices.java:135)
  at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
...
Caused by: org.rascalmpl.uri.UnsupportedSchemeException: Unsupported scheme project
  at org.rascalmpl.uri.URIResolverRegistry.created(URIResolverRegistry.java:617)
  at org.rascalmpl.vscode.lsp.IRascalFileSystemServices.lambda$stat$3(IRascalFileSystemServices.java:130)
  ... 7 more"
```

I think it's because the URI resolver cannot find the new project in the registered projects for the `project` scheme.

**Comment by DavyLandman** [comment]
This has been fixed a while back. Closing it.
