### ISSUE TITLE
InvocationTargetException on missing RASCAL.MF

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-language-servers#96]
Trying to open a Rascal terminal when a project does not have a `RASCAL.MF` file leaks an internal stack trace

```
2021-11-24 10:07:24,038 [pool-3-thread-1] ERROR - org.eclipse.lsp4j.jsonrpc.RemoteEndpoint Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67) ~[rascal-lsp.jar:?]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120) ~[rascal-lsp.jar:?]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261) [rascal-lsp.jar:?]
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190) [rascal-lsp.jar:?]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194) [rascal-lsp.jar:?]
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94) [rascal-lsp.jar:?]
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113) [rascal-lsp.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65) ~[rascal-lsp.jar:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at org.rascalmpl.interpreter.utils.RascalManifest.jarify(RascalManifest.java:324) ~[rascal.jar:?]
	at org.rascalmpl.interpreter.utils.RascalManifest.manifest(RascalManifest.java:290) ~[rascal.jar:?]
	at org.rascalmpl.interpreter.utils.RascalManifest.getProjectName(RascalManifest.java:297) ~[rascal.jar:?]
	at org.rascalmpl.library.util.PathConfig.fromSourceProjectRascalManifest(PathConfig.java:448) ~[rascal.jar:?]
	at org.rascalmpl.vscode.lsp.BaseLanguageServer$ActualLanguageServer.supplyProjectCompilationClasspath(BaseLanguageServer.java:210) ~[rascal-lsp.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65) ~[rascal-lsp.jar:?]
	... 11 more
```

**Comment by DavyLandman** [comment]
Looks like an issue inside [usethesource/rascal](/usethesource/rascal) ?

> 	at org.rascalmpl.interpreter.utils.RascalManifest.jarify(RascalManifest.java:324) ~[rascal.jar:?]

**Comment by rodinaarssen** [comment]
The problem seems to be that `ShellEvaluatorFactory::inferProjectRoot` returns null: https://github.com/usethesource/rascal-language-servers/blob/db246eb4596f792b795642abfe63edf21614194a/rascal-lsp/src/main/java/org/rascalmpl/vscode/lsp/BaseLanguageServer.java#L209

**Comment by DavyLandman** [comment]
aha, interesting, indeed
